### ISSUE TITLE
Can't install on Ubuntu 17.04, 17.10, Ubuntu missing dependency package qtdeclarative5-dialogs-plugin

### ISSUE THREAD

**Issue by mprotic** [wang-bin/QtAV#1002]
sudo add-apt-repository ppa:wbsecg1/qtav ... OK
sudo apt-get update ... OK
apt-get install libqtav libqtavwidgets qml-module-qtav qtav-players

Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qtav-players : Depends: qtdeclarative5-dialogs-plugin but it is not installable
                Depends: qtdeclarative5-controls-plugin but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by KekcuHa** [comment]
I faced the same issue - can not install qtav-players package on Ubuntu 17.10 with "qtdeclarative5-controls-plugin but it is not installable" message.

**Comment by paul-h** [comment]
Same here. It would be nice to get this fixed.

Looks like all the qt5declarative*-plugin packages are transitional dummy packages which can now be safely removed.

**Comment by paul-h** [comment]
Not tested just an educated guess but I think you need to move artful here
https://github.com/wang-bin/QtAV/blob/master/debian/ubuntu.sh#L15
to the end of the list.

And  add another sed like here
https://github.com/wang-bin/QtAV/blob/master/debian/ubuntu.sh#L25 
to change qtdeclarative5-dialogs-plugin for qml-module-qtquick-dialogs

**Comment by wang-bin** [comment]
Try again, should be fixed

**Comment by mprotic** [comment]
No, still not installing, qtdeclarative5-dialogs-plugin is still there.
Can you try second suggestion from paul-h comment ?

**Comment by wang-bin** [comment]
It's changed as paul-h suggested. Are you using 17.10? I can only update for ubuntu LTS and latest version.

**Comment by mprotic** [comment]
Yes, 17.10, tested on a clean install. This is what i did:

sudo add-apt-repository ppa:wbsecg1/qtav
sudo apt-get update
sudo apt-get install libqtav libqtavwidgets qml-module-qtav qtav-players

Got same error.

Looking at your commit, it seems that you've only changed line #15 and not line #25 - proposed changing qtdeclarative5-dialogs-plugin (which is missing in 17.10) to qml-module-qtquick-dialogs (if I understood correctly paul-h suggestion, and your commit)

**Comment by wang-bin** [comment]
I forgot to replace qtdeclarative5-dialogs-plugin. now fixed
