### ISSUE TITLE
Deprecated API Usage when upload to MacStore

### ISSUE THREAD

**Issue by rgbFrank** [wang-bin/QtAV#1218]
My mac application contains the QtAV library 1.11. It works fine, but when you send the release to the AppStore store, an error comes ...

ITMS-90300: Deprecated API Usage - Apple will stop accepting submissions of apps that use QuickTime or QTKit APIs starting from $rejectInkFrameworkFrom .

Anyone can help me?

**Comment by wang-bin** [comment]
done

**Comment by rgbFrank** [comment]
Hello, I rebuild QtAV with latest version 1.13.0, but it still failed when upload to Mac AppStore. I try to create an demo project which only contain "mainwindow", and it is same problem.

--------------------------------
#include "mainwindow.h"
#include "ui_mainwindow.h"
#include <QtAV>

MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    QtAV::AVPlayer *m_avPlayer = new QtAV::AVPlayer;

}

MainWindow::~MainWindow()
{
    delete ui;
}

--------------------------------
Dear Developer,

We identified one or more issues with a recent delivery for your app, "IP Doorphone" 1.0.0 (20190715). Please correct the following issues, then upload again.

ITMS-90300: Deprecated API Usage - Apple will stop accepting submissions of apps that use QuickTime or QTKit APIs .

Best regards,

The App Store Team
--------------------------------

**Comment by wang-bin** [comment]
which ffmpeg version do you use? can you show me libQtAV link command?

**Comment by rgbFrank** [comment]
It fixed by update ffmpeg to latest version. Thank you!

**Comment by pierrexn** [comment]
Hello, 
which ffmpeg version do you use, i have such problem. I've tried with libavcodec 58.60.100 & libavformat 58.34.101

**Comment by rgbFrank** [comment]
> Hello,
> which ffmpeg version do you use, i have such problem. I've tried with libavcodec 58.60.100 & libavformat 58.34.101

update both QtAV and ffmpeg to latest version

**Comment by pierrexn** [comment]
I use QtAV 1.13, and prebuilt FFmpeg libraires 4.2, and same problem
