### ISSUE TITLE
libva acceleration crash

### ISSUE THREAD

**Issue by Ilya87** [wang-bin/QtAV#497]
My OS is Arch Linux-ck x86_64 (fully updated kernel 4.1.6). When I choose to use LibVA acceleration - QMLPlayer crashes with the following message. My building script - http://pastebin.com/pjE9Hcy8

libva info: VA-API version 0.38.0
libva info: va_getDriverName() returns 0
libva info: Trying to open /usr/lib/dri/nvidia_drv_video.so
libva info: Found init function __vaDriverInit_0_35
libva info: va_openDriver() returns 0
qrc:///qml/QMLPlayer/main.qml:114: TypeError: Type error
qrc:///qml/QMLPlayer/main.qml:106: TypeError: Type error
[ShaderManager] cache a new shader material type: packed rgb material
vdpau_video: VdpPresentationQueueTargetCreateX115): status 25: A catch-all error, used when no other error code applies.
Segmentation fault (core dumped)

P.S. How to change QMLPlayer and player installation path (it installs to /usr/lib/qt/bin/QMLPlayer instead of /usr/bin/QMLPlayer)?

**Comment by wang-bin** [comment]
What about disabling zero copy? QMLPlayer->Video codec->click 'Zero Copy' twice to make it gray(default it's checked but the button is not in correct color). The performance will be worse than zero copy.

It's using vdpau backend. I only tested intel gpu.

**Comment by Ilya87** [comment]
Yes, now it works, but moving any window leads to terrible lags.

**Comment by wang-bin** [comment]
can you try other players with vaapi? for example mpv: `mpv --hwdec=vaapi file` and `mpv --hwdec=vaapi-copy file`

**Comment by Ilya87** [comment]
Ok, I'll test the behavior this Sunday.

**Comment by Ilya87** [comment]
1920x1080 example:
mpv --hwdec=vaapi - 1% cpu usage of mpv, when moving window only Xorg consumes cpu, no lags;
mpv --hwdec=vaapi-copy 12%-13% cpu usage, when moving window rises up to 20%, no lags.

P.S. Now I can't decode this mp4 example using vaapi in QMLPlayer at all.

**Comment by wang-bin** [comment]
Confirmed. Unfortutunately gdb can't provide any information.

**Comment by wang-bin** [comment]
please try the latest code. I fixed some bugs in my code and no crash for both 0-copy and copy back mode on my computer

**Comment by Ilya87** [comment]
vaapi: destroy display 0x1e94c10
qrc:///qml/QMLPlayer/main.qml:114: TypeError: Type error
qrc:///qml/QMLPlayer/main.qml:106: TypeError: Type error

Still the same bug.

**Comment by wang-bin** [comment]
what's the log?

**Comment by Ilya87** [comment]
http://pastebin.com/kh2K6kdR

**Comment by wang-bin** [comment]
checking profile: h264, Constrained Baseline
    Codec or profile is not supported by the hardware

Show me you `vainfo` result. mpv will use `main` profile for `main` and `constrained baseline`, I don't know why and still check `constrained baseline support`. You can add a line

    { QTAV_CODEC_ID(H264), FF_PROFILE_H264_CONSTRAINED_BASELINE, VAProfileH264Main }

at line 112 in VideoDecoderVAAPI.cpp to let it work.

But it should not crash

**Comment by wang-bin** [comment]
btw, can you share with me your video?

**Comment by Ilya87** [comment]
vainfo: VA-API version: 0.38 (libva 1.6.0)
vainfo: Driver version: Splitted-Desktop Systems VDPAU backend for VA-API - 0.7.4
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileMPEG4Simple            : VAEntrypointVLD
      VAProfileMPEG4AdvancedSimple    : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointVLD
      VAProfileVC1Simple              : VAEntrypointVLD
      VAProfileVC1Main                : VAEntrypointVLD
      VAProfileVC1Advanced            : VAEntrypointVLD

**Comment by wang-bin** [comment]
Adding 1 line code should work

**Comment by Ilya87** [comment]
Yes, but H264 video flickers.

And error (sigfault) on decoding mpeg4 file:

#0  0x00007ffff4eb95f8 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff4ebaa7a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff4eb2417 in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff4eb24c2 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007fffbadd5f1c in ?? () from /usr/lib/dri/nvidia_drv_video.so
#5  0x00007fffdbb9ba12 in vaCreateContext () from /usr/lib/libva.so.1
#6  0x00007fffe0e0c1c0 in QtAV::VideoDecoderVAAPIPrivate::createSurfaces (this=0x138ed60, count=4, pp_hw_ctx=0x891640, 
    w=512, h=384) at /home/ilya/build/lxqt/miam-player/qtav/src/QtAV/src/codec/video/VideoDecoderVAAPI.cpp:607
#7  0x00007fffe0e0d32b in QtAV::VideoDecoderVAAPIPrivate::getBuffer (this=0x138ed60, opaque=0x7fffa0088378, 
    data=0x7fffa0088240) at /home/ilya/build/lxqt/miam-player/qtav/src/QtAV/src/codec/video/VideoDecoderVAAPI.cpp:773
#8  0x00007fffe0ec0780 in QtAV::ffmpeg_get_va_buffer2 (ctx=0xda6040, frame=0x7fffa0088240, flags=1)
    at /home/ilya/build/lxqt/miam-player/qtav/src/QtAV/src/codec/video/VideoDecoderFFmpegHW.cpp:67
#9  0x00007fffdabcfebf in ?? () from /usr/lib/libavcodec.so.56
#10 0x00007fffdab04c26 in ?? () from /usr/lib/libavcodec.so.56
#11 0x00007fffdaa8d424 in ?? () from /usr/lib/libavcodec.so.56
#12 0x00007fffdaa8f43d in ?? () from /usr/lib/libavcodec.so.56
#13 0x00007fffda86b2fa in ?? () from /usr/lib/libavcodec.so.56
#14 0x00007fffdab03c3b in ?? () from /usr/lib/libavcodec.so.56
#15 0x00007ffff5ac74a4 in start_thread () from /usr/lib/libpthread.so.0
#16 0x00007ffff4f6f13d in clone () from /usr/lib/libc.so.6

**Comment by Ilya87** [comment]
+error on loading external .ass subs
#0  0x00007ffff4eb95f8 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff4ebaa7a in abort () from /usr/lib/libc.so.6
#2  0x00007ffff4eb2417 in __assert_fail_base () from /usr/lib/libc.so.6
#3  0x00007ffff4eb24c2 in __assert_fail () from /usr/lib/libc.so.6
#4  0x00007fffe0e2edaa in CharDet::chardet_create (this=0x7fff740023f0, pdet=0x7fff74002448)
    at /home/ilya/build/lxqt/miam-player/qtav/src/QtAV/src/subtitle/CharsetDetector.cpp:79
#5  0x00007fffe0e2f063 in CharsetDetector::Private::Private (this=0x7fff740023f0)
    at /home/ilya/build/lxqt/miam-player/qtav/src/QtAV/src/subtitle/CharsetDetector.cpp:120
#6  0x00007fffe0e2e77c in CharsetDetector::CharsetDetector (this=0x7fff8f1fdad0)
    at /home/ilya/build/lxqt/miam-player/qtav/src/QtAV/src/subtitle/CharsetDetector.cpp:148
#7  0x00007fffe0e36b2b in QtAV::Subtitle::Private::readFromFile (this=0x895460, path=...)
    at /home/ilya/build/lxqt/miam-player/qtav/src/QtAV/src/subtitle/Subtitle.cpp:748
#8  0x00007fffe0e34141 in QtAV::Subtitle::load (this=0xdbf390)
    at /home/ilya/build/lxqt/miam-player/qtav/src/QtAV/src/subtitle/Subtitle.cpp:439
#9  0x00007fffe0e34575 in QtAV::Subtitle::Loader::run (this=0x702380)
    at /home/ilya/build/lxqt/miam-player/qtav/src/QtAV/src/subtitle/Subtitle.cpp:474
#10 0x00007ffff60c4593 in ?? () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff60c7a9e in ?? () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff5ac74a4 in start_thread () from /usr/lib/libpthread.so.0
#13 0x00007ffff4f6f13d in clone () from /usr/lib/libc.so.6

**Comment by wang-bin** [comment]
`git submodule update --init` to enable charset detector

mpeg4 crashes for me too, debugging now

**Comment by Ilya87** [comment]
After I installed release (not debug) version with added line - flickering disappeared. I suppose self-bugfix was cased by -O2 (or other) flag which is used during compilation.

**Comment by wang-bin** [comment]
I tested mpv and it does not use vaapi to play mpeg4

**Comment by wang-bin** [comment]
check out the latest code. the profile checking is fixed. also mpeg4 works now (vaapi surfaces are not enough for multi-thread decoding and I increase the surfaces)

**Comment by wang-bin** [comment]
mpv always uses single thread decoding for hardware decoders, so it does not crash. I don't know why mpv does not use vaapi for mpeg2, mpeg4

**Comment by Ilya87** [comment]
Now mpeg4 can be decoded, but crashes at seeking.

**Comment by wang-bin** [comment]
No crash in my tests. But it's possible. I will fix it later.
BTW, I need your `constrained baseline profile` video to test. Can you share with me?

**Comment by wang-bin** [comment]
I need your mpeg4 video too. Maybe it can crash QtAV on my computer

**Comment by wang-bin** [comment]
You can try single thread decoding to see whether it crashes on seek: in VideoDecoderVAAPI.cpp, add

    codec_ctx->thread_count = 1;

at the beginning of `open()`

**Comment by Ilya87** [comment]
```    bool codec_ctx->thread_count = 1; open()  Q_DECL_OVERRIDE;```?
Crashes at compiling. Or it should be in braces?
https://yadi.sk/i/bB6MNaP-iy6Gj - constrained baseline. 
Simply created with ```ffmpeg -i input.mp4 -c:v libx264 -preset fast -profile:v baseline out.mkv``` command.
https://yadi.sk/i/bB6MNaP-iy6Gj - mpeg4

**Comment by wang-bin** [comment]
add `codec_ctx->thread_count = 1;` to line 429

**Comment by wang-bin** [comment]
I tested your mpeg4 video and no crash. what about you?

**Comment by Ilya87** [comment]
I still can't apply your patch. Could you please post normal patch here?
```bool VideoDecoderVAAPIPrivate::open()
{
    if (!prepare()) codec_ctx->thread_count = 1;
        return false;```

**Comment by wang-bin** [comment]
I mean at the beginning of this function

**Comment by Ilya87** [comment]
Even with this new line I get an error when seek (right and left arrows):
"VAAPI - renderer still using all freed up surfaces by decoder. unable to find free surface, trying to allocate a new one"
"createSurfaces 5 512x384"
QMLPlayer: vdpau_video.c:595: vdpau_CreateContext: Проверочное утверждение «obj_surface->va_context == 0xffffffff» не выполнено.

**Comment by wang-bin** [comment]
try the latest code. it should not crash now

**Comment by Ilya87** [comment]
Yes, thank you! Now the problem is solved.
